name: Mobile Web App Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Create build output
      run: |
        mkdir -p dist
        cp -r src/* dist/ 2>/dev/null || echo "No src directory found"
        cp index.html dist/ 2>/dev/null || echo "Using existing index.html"
        ls -la dist/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mobile-web-app
        path: dist/